### ISSUE TITLE
Bamboo.Formatter not implemented

### ISSUE THREAD

**Issue by erincat** [thoughtbot/bamboo#234] opened 2016-12-08 03:59 UTC
I have a code in in my mac OSX laptop that I want to run in windows. 

I copied all of the codes and ran the same line in iex: 
iex> MyApp.Mailer.deliver_now MyApp.Email.sample_email('example@example.com') 

But I get this in windows:
** (Protocol.UndefinedError) protocol Bamboo.Formatter not implemented for 99
    (bamboo) lib/bamboo/formatter.ex:1: Bamboo.Formatter.impl_for!/1
    (bamboo) lib/bamboo/formatter.ex:65: Bamboo.Formatter.format_email_address/2

Any thoughts? Thank you.

**Comment by optikfluffel** [comment] 2016-12-08 08:30
Hey @erincat,
could you try wrapping your email address into `"` instead of `'` since in Elixir single quotes indicate [char lists](http://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#char-lists) and I'm guessing you want to use a string here.

**Comment by erincat** [comment] 2016-12-08 21:42
Yay! It works! thanks @optikfluffel 

I also tried this one in the command line (not in iex),
my_app>mix run -e "MyApp.Mailer.deliver_now MyApp.Email.sample_email('example@example.com')" 
but I get the same error, so I tried changing it to
my_app>mix run -e "MyApp.Mailer.deliver_now MyApp.Email.sample_email("example@example.com")"
but now I get "invalid character '@' in identifier"

**Comment by paulcsmith** [comment] 2016-12-08 21:44
@erincat So the issue is resolved? If so I'll go ahead and close this

**Comment by erincat** [comment] 2016-12-08 21:46
@paulcsmith I still have one last question though, about the invalid character '@' in identifier.

**Comment by paulcsmith** [comment] 2016-12-08 21:50
I think it is getting confused the unescaped quotes. I believe adding `\` before the `"` around the email could fix the issue. Alternatively you could use `iex -S mix` or just `iex` (depending on where you're running it) and do it from there. That's usually what I prefer doing

**Comment by erincat** [comment] 2016-12-08 21:59
Tried it but I get (TokenMissingError). Is there no other way for me to run this code without having to go to iex first?

**Comment by paulcsmith** [comment] 2016-12-08 22:02
@erincat I'm about to head out for the day so you may want to try Elixir Slack or Elixir forums to get more info. That will probably be the best place to get help, especially since this doesn't appear to be a Bamboo specific issue.

I'm going to go ahead and close this for now. If you Slack/forums can't help, feel free to comment here even though it's closer

**Closed by paulcsmith** 2016-12-08 22:02 UTC
