### ISSUE TITLE
Regex Matching with `assert_delivered_with`

### ISSUE THREAD

**Issue by rawkode** [thoughtbot/bamboo#257] opened 2017-02-27 14:17 UTC
Hi,

Really loving your library, so thanks for your hard work! :+1: 

I am trying to test that some variables are being inserted into an email, with:
```elixir
assert_delivered_with(text_body: ~r/Hi David/)
```
```elixir
text_body(EEx.eval_file("priv/emails/welcome.eex", [forename: event["payload"]["forename"]]))
```

to prove that my `EEx` template has inserted the name correctly.

This doesn't seem to work, so I was hoping you'd be able to point me in the right direction?

Thanks

**Comment by jbernardo95** [comment] 2017-03-02 16:25
@rawkode `assert_delivered_with` does not accept regexes, it only accepts string to compare equality.

So partial checks like checking if the email's `text_body` has a certain word(s) is not possible. But I think this would definitely be a nice thing to add.

@paulcsmith What do you think ?

More details and examples here: https://hexdocs.pm/bamboo/Bamboo.Test.html#assert_delivered_with/1

**Comment by paulcsmith** [comment] 2017-03-02 16:42
@rawkode Thanks for the kind words! I'm glad you like it :) 

That helper was designed to be used roughly like this

```elixir
assert_delivered_with(text_body: Emails.my_cool_email(user).text_body)
```

So maybe you could do

```elixir
body = text_body(EEx.eval_file("priv/emails/welcome.eex", ["David"])) # or however you create emails
assert_delivered_with(text_body: body) # That way it checks the whole body
```

If the email generates something random so the email body isn't an exact match, you could make a helper function yourself by using [`Bamboo.Test.delivered_emails()`](https://github.com/thoughtbot/bamboo/blob/fe90aa68aeefdb181b25ba8910202e2c0918a7c5/lib/bamboo/test.ex#L246-L252). 

For now you will need to copy paste that function to use it in your tests since it is private. In the future it would probably be good if I made `Bamboo.Test.delivered_emails` function public so people can write their own helpers more easily, for now though it would be something like this:

```elixir
defp delivered_emails do
  {:messages, messages} = Process.info(self(), :messages)

  for {:delivered_email, _} = email_message <- messages do
    email_message
  end
end

def assert_body_contains(body) do
  Enum.any? delivered_emails(), fn(email) ->
    assert email.html_body =~ body
    assert email.text_body =~ body
  end
end
```

I would add something like this to Bamboo if someone made a PR :D If not I'll probably add it myself, but I'm not sure when I could get to it.

I'm going to go ahead and close this, but please comment on if this helped you or if you have further questions

**Closed by paulcsmith** 2017-03-02 16:42 UTC

**Comment by rawkode** [comment] 2017-03-02 16:46
Thanks, @paulcsmith; that certainly helps.

I'll try and implement this and get you a PR :smile:
