### ISSUE TITLE
HTTP 406 Not Acceptable - SendGrid sending email

### ISSUE THREAD

**Issue by sergiotapia-papa** [thoughtbot/bamboo#542] opened 2020-07-13 21:29 UTC
In our project we've started receiving these errors when trying to send any transactional email. 

>"<html>\r\n<head><title>406 Not Acceptable</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>406 Not Acceptable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"

The params we send:

>%{"content" => [%{"type" => "text/plain", "value" => "some text value email."}, %{"type" => "text/html", "value" => "some html..." <> ...}], "from" => %{"email" => "noreply@joinpapa.com", "name" => "Team Papa"}, "key" => "[FILTERED]", "personalizations" => [%{"to" => [%{"email" => "abc@abc.com"}]}], "subject" => "Reset your password"}

Did a Sendgrid API change break this package?

**Comment by sergiotapia-papa** [comment] 2020-07-20 21:31
![image](https://user-images.githubusercontent.com/52164116/87988678-bc454d00-caae-11ea-9217-0c651a90a090.png)

We're still seeing these HTTP 406 errors randomly.

**Comment by germsvel** [comment] 2020-07-21 12:24
Thanks for opening this @sergiotapia-papa. I wonder if others are seeing similar errors? Is there any more info you can provide about how to reproduce this error? I'm not sure I have much to go on.

**Comment by sergiotapia-papa** [comment] 2020-07-21 13:27
I'm going to create a custom strategy to log more information about the error and try to find a common thread.

**Comment by germsvel** [comment] 2020-07-21 13:56
Thank you! That would be so helpful.

**Comment by sergiotapia-papa** [comment] 2020-07-27 21:30
I'm still getting these errors and the custom strategy isn't giving any further information. 

```
There was a problem sending the email through the SendGrid API.

Here is the response:

"<html>\r\n<head><title>406 Not Acceptable</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>406 Not Acceptable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"

Here are the params we sent:

%{"from" => %{"email" => "automation@myapp.com"}, "key" => "[FILTERED]", "personalizations" => [%{"dynamic_template_data" => %{"client_name" => "sergiotest", "date_of_birth" => "2020-07-27T21:26:50.019Z", "description" => "sergiotest please ignore.", "location" => "sergiotest", "member_id" => "sergiotest", "member_name" => "sergiotest", "name_of_pal" => "sergiotest", "requester" => "sergiotest", "type" => "theft", "visit_date" => "2020-07-27T21:26:50.019Z"}, "to" => [%{"email" => "member@myapp.zendesk.com"}]}], "template_id" => "d-a3469d2af1934877777772d95e3e02fd"}
```

I'll need to reach out to sendgrid.

**Comment by germsvel** [comment] 2020-07-29 13:03
Thanks for keeping us informed @sergiotapia-papa! Let me know if Sendgrid is able to help.

**Comment by sergiotapia-papa** [comment] 2020-08-02 00:45
@germsvel we needed to upgrade the bamboo package as a PR added the application/json header to the sendgrid strategy. Weird how some emails went through and some didn't though, on sendgrid's side.

**Comment by germsvel** [comment] 2020-08-03 12:27
Thanks so much for digging into it and letting us know the cause for those errors @sergiotapia-papa! Glad you got it resolved.

**Comment by jatin759** [comment] 2020-08-04 08:37
@germsvel  @sergiotapia-papa hey, I am still getting the same error after updating deps as well. I am using `{:bamboo, github: "thoughtbot/bamboo"}` in deps and putting the header like this:  `email |> put_header("accept", "application/json")`

Am I doing anything wrong?

**Comment by germsvel** [comment] 2020-08-05 13:59
@jatin759 I reopened this, but I'm not sure how else to help. 

I _think_ the PR @sergiotapia-papa mentioned was  https://github.com/thoughtbot/bamboo/pull/529, where Bamboo added that header to the Sendgrid adapter. So, you might not need to add the `put_header("accept", "application/json")` if you're using a version of Bamboo that includes that commit.

Can you provide any other info about the error you are seeing? What version of bamboo do you have in your `mix.lock` file?

**Comment by sergiotapia-papa** [comment] 2020-08-05 16:47
That is correct, we just had to upgrade the package and that fixed it for us.

**Comment by germsvel** [comment] 2020-08-12 19:52
@jatin759 do you have any other information that might help us resolve this? Otherwise, it seems like the issue might be resolved by updating to the version of bamboo that has the correct headers.

**Comment by jatin759** [comment] 2020-08-13 12:00
@germsvel yes the issue has been resolved for now without making any changes that I mentioned while reopening this issue. I  am afraid if this may again come. Let's see how it goes.
Thanks @sergiotapia-papa @germsvel

**Comment by germsvel** [comment] 2020-08-13 13:02
Sounds good! Let us know if this comes up again. For now, I'll close this issue.

**Closed by germsvel** 2020-08-13 13:02 UTC
