### ISSUE TITLE
Test attachments locally with LocalAdapter

### ISSUE THREAD

**Issue by RicardoBrazao** [thoughtbot/bamboo#349] opened 2018-01-31 11:53 UTC
Hi there,

I was looking at testing that the attachment is sent in an email, and was greeted with:
```
(RuntimeError) the Elixir.Bamboo.LocalAdapter does not support attachments yet.
    (bamboo) lib/bamboo/mailer.ex:173: Bamboo.Mailer.validate_attachment_support/2
    (bamboo) lib/bamboo/mailer.ex:158: Bamboo.Mailer.validate_and_normalize/2
    (bamboo) lib/bamboo/mailer.ex:130: Bamboo.Mailer.deliver_later/3
```

After looking at the code, and other the adapters that allow attachments, I can see that in the LocalAdapter there is a missing function
```
@doc false
  def supports_attachments?, do: true
```
Is it the case that, if I add it to the LocalAdapter we could test the attachments locally? Or am I missing some more things that need to be done?

**Comment by Sgoettschkes** [comment] 2018-09-11 12:06
I can't reproduce this bug. Even with the LocalAdapter it's possible to put attachments to the email but they don't show up in the local web interface.

**Comment by germsvel** [comment] 2020-10-26 13:53
I believe this is resolved by https://github.com/thoughtbot/bamboo/pull/553, so I'm going to close this. 

If I misunderstood the issue, and we should reopen this, please let me know! I'd be happy to do it.

**Closed by germsvel** 2020-10-26 13:53 UTC
Labels: non-breaking, queued
