### ISSUE TITLE
Bamboo.EmailPreviewPlug doesn't pass content-type (it renders as text in Chrome)

### ISSUE THREAD

**Issue by Qqwy** [thoughtbot/bamboo#174] opened 2016-06-04 15:52 UTC
I'm on Linux Mint 17.2.

Using FireFox(45.0), the Bamboo.EmailPreviewPlug looks like this:

![screenshot from 2016-06-04 17 50 09](https://cloud.githubusercontent.com/assets/5345745/15800555/d034560c-2a7c-11e6-87a8-43f9dcffed0e.png)

However, in chrome (Chromium  49.0.2623.108)  it looks like this:

![screenshot from 2016-06-04 17 50 41](https://cloud.githubusercontent.com/assets/5345745/15800557/ddce2cd4-2a7c-11e6-8ee9-4530abde9775.png)

This is probably caused by not passing a content-type in the return value, which makes Chrome fallback to 'text' behaviour.

**Comment by paulcsmith** [comment] 2016-07-01 20:36
@Qqwy Thanks for reporting this. I'll try to tackle this myself, but if someone else wants to take a swing at it, that would be wonderful!

**Comment by codyjroberts** [comment] 2016-07-02 15:42
I can't seem to reproduce this.

Chrome Version 51.0.2704.79
Phoenix 1.2.0
Bamboo 0.6.0

**Comment by paulcsmith** [comment] 2016-07-07 19:46
Hmm, I wonder if the issue is that @Qqwy has the plug in a pipeline that sets the content type? @Qqwy can you show the router file so we can see if there might be something there that leads us to figuring out this bug?

**Comment by paulcsmith** [comment] 2016-07-29 14:54
Fixed by #203

**Comment by paulcsmith** [comment] 2016-07-29 14:54
Thanks for submitting the issue @Qqwy. The fix will go out in the next release!

**Closed by paulcsmith** 2016-07-29 14:54 UTC
Labels: bug
